down:
  headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
    Connection: keep-alive
  cookies:
    UOJSESSID: 3htc4g05jcb0oa4pn5adtjhe3n
  min_id: 3932620
  base_url: http://oj.daimayuan.top/submission/
  max_404_count: 15
  timeout: 10
  batch_size: 8
  retry:
    max_retries: 3
    backoff_factor: 0.5
    status_forcelist: [500, 502, 503, 504]
  cache:
    expire: 100000
    timeout: 1    
    retry: true   

general:
  cache_file: cache.json
  outtemplate: app/templates/standing.html
  waitingfile: waiting.html
  cache_dir: ./cache
  secretkey: fcfff06f-aa92-4db5-b0b7-269c066c2d49

log:
  folder: ./logs
  file: ./logs/log
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  max_bytes: 10485760
  backup_count: 5

models:
  save_minute: 10

task:
  savetime: 600
